---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-intl', 'php-zip', 'php-imagick', 'php-gmp', 'php-bcmath' ]

#MySQL Settings
mysql_root_password: "root"
mysql_db: "ncdb"
mysql_user: "ncuser"
mysql_password: "ncuser"

#HTTP Settings
http_host: "nc"
http_conf: "nc.conf"
http_port: "80"
