# El nombre de host usado por Apache y Nginx
http_host: sw

# Usuario de la aplicaci칩n que tendr치 permisos sobre los directorios
app_user: www-data

# Nombre del archivo de configuraci칩n de Apache
http_conf: apache.conf

# Deshabilitar el sitio por defecto de Apache
disable_default: true

# Nombre del archivo de configuraci칩n de Nginx
nginx_conf: proxy
